# Generated by Django 5.0.2 on 2024-02-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0003_alter_article_title_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='contente',
            new_name='content',
        ),
    ]
